basic.showString("Hello!")
basic.showIcon(IconNames.Happy)
basic.pause(100)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Run, 45)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Red)
basic.pause(200)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_SpinRight, 45)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Green)
basic.pause(200)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_SpinLeft, 45)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Blue)
basic.pause(200)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Back, 45)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.White)
basic.pause(200)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Back, 45)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.OFF)
basic.forever(function () {
	
})
